### ISSUE TITLE
老哥，无法删除元素，怎么回事？

### ISSUE THREAD

**Issue by CYC666** [songmenglong/MyInsight_iOS#1]
/// 删除单个学生
    static func delete(student: Student) -> Void {
        // 是否有数据库表
        self.createTable()
        // 事务
//        try! self.dbQueue.inTransaction { (db) -> Database.TransactionCompletion in
//            do {
//                // 删除数据
//                try student.delete(db)
//                return Database.TransactionCompletion.commit
//            } catch {
//                return Database.TransactionCompletion.rollback
//            }
//        }
        
        try! self.dbQueue.write({ (db) -> Void in
            try student.delete(db)
        })
        
        
    }

这里，执行之后，再次查询，对应的元素还存在数据库。该如何处理呢？

**Comment by CYC666** [comment]
我改成了这样才行，我丢

try self.dbQueue.write({ db in
                
                try db.execute(sql: "delete from ETHWalletModel where walletId=:walletId", arguments: ["walletId" : wallet.walletId])
                
            })

**Comment by songmenglong** [comment]
可定义主键，根据主键ID删除
